# Generated by Django 2.2.1 on 2019-06-11 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200, verbose_name='FIRST NAME')),
                ('last_name', models.CharField(default='', max_length=200, verbose_name='LAST NAME')),
                ('biography', models.TextField(default='', max_length=2000, verbose_name='BIOGRAPHY')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='FACEBOOK URL')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('google_plus_url', models.URLField(blank=True, null=True)),
                ('author_image', models.ImageField(upload_to='author/')),
                ('image_gallery', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
